language: android
jdk: oraclejdk8
sudo: false

android:
  components:
    - tools
    - build-tools-27.0.0
    - extra-android-m2repository
    - android-26
    - sys-img-armeabi-v7a-addon-google_apis-google-26
